### ISSUE TITLE
Some uncritical build warnings

### ISSUE THREAD

**Issue by tsufz** [schymane/ReSOLUTION#1]
* installing *source* package 'ReSOLUTION' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Note: possible error in 'view.image.2d(mol, width = 150, ': unused arguments (width = 150, height = 150) 
** help
*** installing help indices
  converting help for package 'ReSOLUTION'
    finding HTML links ... done
    CompToxCSVtoLocalCSVterms               html  
    CompToxFullCSVtoLocalCSVterms           html  
    CompToxSDFtoLocalSDFterms               html  
    CompToxXLStoLocalCSVterms               html  
    ExplFormulas2AnnoMZ                     html  
    ExplPeaks2MSMS                          html  
    IDfromFilePath                          html  
    MBFileToVector                          html  
    MetFragConfig.CompToxCSV                html  
    MetFragConfig.CompToxExportSDF          html  
    MetFragConfig                           html  
    MetFragConfig.formula                   html  
    finding level-2 HTML links ... done

    SpecComp.OrgMassSpecR                   html  
    addMissingInChIKeys.CSV                 html  
    addMsMs                                 html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc7d162e32/schymane-ReSOLUTION-3b313a0/man/addMsMs.Rd:33: missing link 'RMassBank'
    addMsMs.oldRMB                          html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc7d162e32/schymane-ReSOLUTION-3b313a0/man/addMsMs.oldRMB.Rd:33: missing link 'RMassBank'
    addStructToPlot                         html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc7d162e32/schymane-ReSOLUTION-3b313a0/man/addStructToPlot.Rd:13: missing link 'rcdk'
    chemistry2expression                    html  
    extractMS1.RMBarchive                   html  
    extractMS1and2.RMBarchive               html  
    fixMzIntColNames                        html  
    getMBPeaksAnnos                         html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc7d162e32/schymane-ReSOLUTION-3b313a0/man/getMBPeaksAnnos.Rd:27: missing link 'RMassBank'
    getMBRecordEntry                        html  
    getMBRecordInfo.MetFragConfig           html  
    getMBRecordInfo                         html  
    getMBRecordPeakAnnotations              html  
    getMBRecordPeaks                        html  
    nontargetWrap                           html  
    plotAdductEICs                          html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc7d162e32/schymane-ReSOLUTION-3b313a0/man/plotAdductEICs.Rd:72: missing link 'rcdk'
    plotAnnoSpectrum                        html  
    plotEICs                                html  
    plotMS                                  html  
    plotSpectra                             html  
    plotSpectrum                            html  
    process.sdf.file                        html  
    runMetFrag                              html  
    screen.homol                            html  
    screenSuspects                          html  
    trimAnnotation                          html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc7d162e32/schymane-ReSOLUTION-3b313a0/man/trimAnnotation.Rd:28: missing link 'RMassBank'
** building package indices
** testing if installed package can be loaded
* DONE (ReSOLUTION)

> sessionInfo() R version 3.5.0 (2018-04-23) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows >= 8 x64 (build 9200)  Matrix products: default  locale: [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] devtools_1.13.5  loaded via a namespace (and not attached):  [1] httr_1.3.1     compiler_3.5.0 R6_2.2.2       tools_3.5.0    withr_2.1.2    rstudioapi_0.7 curl_3.2        [8] yaml_2.1.18    memoise_1.1.0  git2r_0.21.0   digest_0.6.15
--
 
> | >

**Comment by schymane** [comment]
Again warnings not errors? It seems to have installed?

**Comment by tsufz** [comment]
Yes, builds. That's why uncritical.

**Comment by schymane** [comment]
But they are warnings, not errors, that’s what I mean … if it is an error it shouldn’t build

**Comment by tsufz** [comment]
sure

**Comment by schymane** [comment]
Closed with https://github.com/schymane/ReSOLUTION/commit/44b27cec890942eabcfd7e3208ad7ed28418838a
